#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# Fimbulwinter Lite — CI: File or Refresh the Mod-Updates Issue
#
# Glue for .github/workflows/check-updates.yml. Takes the JSON
# update list that update-mods.sh writes to GITHUB_OUTPUT and
# keeps exactly one open issue labelled "mod-updates" in sync
# with it: the existing issue is rewritten if present, otherwise
# a new one is created. Exits 0 without touching anything when
# the list is empty.
#
# Env:
#   UPDATE_LIST   JSON array of {mod, current, latest} objects
#   GH_TOKEN      Token with issues:write (github.token in Actions)
#   GH_REPO       owner/repo (defaults to GITHUB_REPOSITORY)
#
# Requires: bash, jq, gh
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

LABEL="mod-updates"

: "${UPDATE_LIST:?UPDATE_LIST (JSON array) is required}"
: "${GH_TOKEN:?GH_TOKEN is required}"
export GH_REPO="${GH_REPO:-${GITHUB_REPOSITORY:?GH_REPO or GITHUB_REPOSITORY is required}}"

for tool in jq gh; do
    command -v "$tool" >/dev/null || { echo "Required tool missing: $tool" >&2; exit 1; }
done

count=$(jq -e 'length' <<<"$UPDATE_LIST") || { echo "UPDATE_LIST is not a JSON array" >&2; exit 1; }
if [ "$count" -eq 0 ]; then
    echo "No updates in UPDATE_LIST; nothing to file."
    exit 0
fi

title="${count} Thunderstore mod update(s) available"
run_url="${GITHUB_SERVER_URL:-https://github.com}/${GH_REPO}/actions/runs/${GITHUB_RUN_ID:-}"

body=$(
    echo "## Thunderstore Mod Updates"
    echo
    echo "The weekly update check found **${count}** mod(s) with newer versions on Thunderstore."
    echo
    echo "| Mod | Current | Latest |"
    echo "|-----|---------|--------|"
    jq -r '.[] | "| `\(.mod)` | \(.current) | **\(.latest)** |"' <<<"$UPDATE_LIST"
    echo
    echo "### Next Steps"
    echo
    echo "1. Review the [Thunderstore changelogs](https://thunderstore.io/c/valheim/) for breaking changes"
    echo "2. Update versions in \`thunderstore.toml\`"
    echo "3. Install via r2modman, run the game, check for new configs"
    echo "4. Update \`config/\` if needed"
    echo "5. Update CHANGELOG.md and README.md"
    echo
    echo "*Auto-generated by the [check-updates workflow](${run_url})*"
)

# Make sure the label exists so issue creation cannot fail on it.
gh label create "$LABEL" --color "0E8A16" --force \
    --description "Thunderstore dependencies with newer versions available" >/dev/null

existing=$(gh issue list --label "$LABEL" --state open --limit 1 --json number --jq '.[0].number // empty')

if [ -n "$existing" ]; then
    gh issue edit "$existing" --title "$title" --body "$body" >/dev/null
    echo "Updated existing issue #${existing}"
else
    gh issue create --title "$title" --body "$body" --label "$LABEL"
fi
