#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# Fimbulwinter Lite — CI: File or Refresh the Mod-Updates Issue
#
# Glue for .github/workflows/check-updates.yml. Takes the JSON
# update list that update-mods.sh writes to GITHUB_OUTPUT and
# keeps at most ONE open issue labelled "mod-updates":
#
#   updates, same as the open issue   -> nothing happens
#   updates, different / no open one  -> older open issues are closed
#                                        as superseded, a new one is filed
#   no updates                        -> any open issue is closed as resolved
#
# "Same" is decided by a fingerprint of the update list embedded in
# the issue body, so a daily run does not churn issues while the
# set of pending updates is unchanged.
#
# Env:
#   UPDATE_LIST   JSON array of {mod, current, latest} objects
#   GH_TOKEN      Token with issues:write (github.token in Actions)
#   GH_REPO       owner/repo (defaults to GITHUB_REPOSITORY)
#
# Requires: bash, jq, gh, sha256sum
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

LABEL="mod-updates"

: "${UPDATE_LIST:?UPDATE_LIST (JSON array) is required}"
: "${GH_TOKEN:?GH_TOKEN is required}"
export GH_REPO="${GH_REPO:-${GITHUB_REPOSITORY:?GH_REPO or GITHUB_REPOSITORY is required}}"

for tool in jq gh sha256sum; do
    command -v "$tool" >/dev/null || { echo "Required tool missing: $tool" >&2; exit 1; }
done

count=$(jq -e 'length' <<<"$UPDATE_LIST") || { echo "UPDATE_LIST is not a JSON array" >&2; exit 1; }
run_url="${GITHUB_SERVER_URL:-https://github.com}/${GH_REPO}/actions/runs/${GITHUB_RUN_ID:-}"

# Open issues carrying our label, newest first, with their fingerprint.
# Output lines: "<number>\t<fingerprint-or-empty>"
open_issues=$(gh issue list --label "$LABEL" --state open --limit 50 --json number,body \
    --jq '.[] | "\(.number)\t\((.body | capture("<!-- fimbulwinter-updates:(?<fp>[0-9a-f]+) -->") | .fp) // "")"')

# ── No updates: resolve anything still open ─────────────────────
if [ "$count" -eq 0 ]; then
    if [ -z "$open_issues" ]; then
        echo "All mods up to date; no open ${LABEL} issue to close."
        exit 0
    fi
    while IFS=$'\t' read -r number _; do
        [ -n "$number" ] || continue
        gh issue close "$number" --reason completed \
            --comment "All pinned mods are up to date as of the [latest check](${run_url}). Closing." >/dev/null
        echo "Closed issue #${number} (resolved)"
    done <<<"$open_issues"
    exit 0
fi

# ── Updates: skip if unchanged, otherwise supersede ─────────────
fingerprint=$(jq -cS 'sort_by(.mod)' <<<"$UPDATE_LIST" | sha256sum | cut -c1-16)

if grep -q $'\t'"${fingerprint}\$" <<<"$open_issues"; then
    number=$(grep $'\t'"${fingerprint}\$" <<<"$open_issues" | head -1 | cut -f1)
    echo "Open issue #${number} already lists these ${count} update(s); nothing to do."
    exit 0
fi

title="${count} Thunderstore mod update(s) available"
body=$(
    echo "<!-- fimbulwinter-updates:${fingerprint} -->"
    echo "## Thunderstore Mod Updates"
    echo
    echo "The daily update check found **${count}** mod(s) with newer versions on Thunderstore."
    echo
    echo "| Mod | Current | Latest |"
    echo "|-----|---------|--------|"
    jq -r '.[] | "| `\(.mod)` | \(.current) | **\(.latest)** |"' <<<"$UPDATE_LIST"
    echo
    echo "### Next Steps"
    echo
    echo "1. Review the [Thunderstore changelogs](https://thunderstore.io/c/valheim/) for breaking changes"
    echo "2. Update versions in \`thunderstore.toml\`"
    echo "3. Install via r2modman, run the game, check for new configs"
    echo "4. Update \`config/\` if needed"
    echo "5. Update CHANGELOG.md and README.md"
    echo
    echo "*Auto-generated by the [check-updates workflow](${run_url}). Superseded automatically when the update set changes.*"
)

# Make sure the label exists so issue creation cannot fail on it.
gh label create "$LABEL" --color "0E8A16" --force \
    --description "Thunderstore dependencies with newer versions available" >/dev/null

new_url=$(gh issue create --title "$title" --body "$body" --label "$LABEL")
new_number="${new_url##*/}"
echo "Created issue #${new_number}: ${new_url}"

while IFS=$'\t' read -r number _; do
    [ -n "$number" ] || continue
    gh issue close "$number" --reason "not planned" \
        --comment "Superseded by #${new_number} (the set of pending updates changed)." >/dev/null
    echo "Closed issue #${number} (superseded by #${new_number})"
done <<<"$open_issues"
